name: 'Fetch Org Repositories'
description: 'Collect data about all GitHub Repositories attached to a GitHub Organization.'
author: 'fgerthoffert'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: green

# Define your inputs here.
inputs:
  org:
    description: 'A GitHub Organization'
    required: true
  token:
    description: 'A GitHub Personal API Token'
    required: true
  max_query_nodes:
    description: 'Maximum number of nodes to fetch per GraphQL query'
    required: true
    default: 30
  filter_topics:
    description: 'Comma separated list of topics to filter repositories by. Use EMPTY to filter by repositories without topics'
    default: ''
    required: false
  filter_operand:
    description: 'OR, AND operand to filter repositories by topics'
    default: 'AND'
    required: false
  filter_ignore_archived:
    description: 'By default, archived repositories are not included'
    default: 'true'
    required: false
  artifact_name:
    description: 'Name of the JSON file containing the repositories data'
    default: 'repositories.json'
    required: false
  artifact_retention:
    description: 'Number of days to retain the artifact'
    default: '2'
    required: false

# Define your outputs here.
outputs:
  artifact_filepath:
    description: 'Filepath of the JSON file containing the repositories data'

runs:
  using: node20
  main: dist/index.js
